### ISSUE TITLE
Is it possible to populate the main context menu?

### ISSUE THREAD

**Issue by ZzzZombi** [NumeriusNegidius/Context-Search#1]
I'm talking about putting search engines directly in the context menu as opposed to under the "Context Search" sub-menu.

When I add just one bookmark under "Searches" it puts the engine directly in the context menu and not in CS sub-menu.

Edit: Just found this on [Developer](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus) page:

> **If you have created more than one context menu item, then the items will be placed in a submenu. The submenu's parent will be labeled with the name of the extension.** In this case, if you have also specified an icon, then the submenu's parent will get the icon, and the items themselves will not get any icon.

Chrome also does it this way. Though I don't understand, why not just let us put multiple main items to context menus.

**Comment by NumeriusNegidius** [comment]
Yeah, it doesn't seem possible with the current spec, unfortunately. If they add the functionality I might revisit/reopen this. Thanks for the feedback though!

**Comment by theres-waldo** [comment]
I filed a Firefox issue about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1396346

**Comment by theres-waldo** [comment]
> I filed a Firefox issue about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1396346

Unfortunately, it was closed as a duplicate of [another issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1294429) which has been marked as WONTFIX. 

*sigh*
