### ISSUE TITLE
Select target with other mouse buttons

### ISSUE THREAD

**Issue by somini** [NumeriusNegidius/Context-Search#11]
It would be nice if you could select the target of the new page with the left/right/middle mouse button.

In Context Search X this is configurable, but my particular settings:
- Left Mouse Button: Open in new tab in the background (don't change to the newly opened page)
- Middle Mouse Button: Open in new tab in the forground (change to the newly opened page)
- Right Mouse Button: Open in the current tab

I'm not sure the new WebExtensions API allows for this level of control.

---
PS: I'm a refugee from Context Search X, many thanks for taking the time to make this.

**Comment by NumeriusNegidius** [comment]
Unfortunately, I don't have a three button mouse to test this with. Also, I am a sucker for UX consistency. 

That said, I'd at least like the extension to support (like Firefox does) the middle mouse button click to open the search in a new tab. But I can't make it happen if I can't test it.

**Comment by somini** [comment]
That's fair. One you get middle mouse button working I can implement this issue, I have this in my muscle memory and it would take a long time to get used to another interface.

**Comment by somini** [comment]
I looked around and it seems this is not possible:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus/OnClickData

I tried to debug the extension (this is really easy: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging) and I can't even right-click the context menus, there are no events fired anywhere. Nor is any even fired when you click the top-level menu.

**Comment by somini** [comment]
This should be tagged: "external API issue"

**Comment by NumeriusNegidius** [comment]
Closing this for now. Will reopen if API allows for it.

**Comment by NumeriusNegidius** [comment]
This seems to be fixed in the API now, according to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData). Reopening

**Comment by NumeriusNegidius** [comment]
This is now fixed in the upcoming version, trying to keep as close to Firefox default behavior (as listed on http://mzl.la/1xKrRYF) as possible.
