### ISSUE TITLE
Place the context menu item next to the built-in Search item

### ISSUE THREAD

**Issue by theres-waldo** [NumeriusNegidius/Context-Search#15]
The context menu item added by this extension is at the bottom of the context menu.

I think it would be more natural to have it next to (meaning right below or above) the built-in "Search <default search engine> for..." context menu item.

(That would also match the behaviour of the legacy Context Search and Context Search X extensions.)

**Comment by NumeriusNegidius** [comment]
The WebExtensions API unfortunately doesn't allow for that level of manipulation. Add-on context menus are placed at the bottom by Firefox design. 

If this behavior is changed in the future, I'll consider reopening this issue.

**Comment by theres-waldo** [comment]
It looks like this Firefox issue is relevant: https://bugzilla.mozilla.org/show_bug.cgi?id=1325758
