### ISSUE TITLE
If there is only one search bookmark, don't use a submenu

### ISSUE THREAD

**Issue by theres-waldo** [NumeriusNegidius/Context-Search#17]
I understand that an extension can't create multiple top-level context menu items (issue #1).

However, if there is only one search bookmark in the "Searches" folder, so that the submenu would only have the one element, I think it would make sense to save the user a click by not creating a submenu at all, and just using the top-level context menu item.

**Comment by NumeriusNegidius** [comment]
Agreed. I'll look in to it. Perhaps the label then should be "Search for: X... on Y".

**Comment by NumeriusNegidius** [comment]
I've reconsidered. There are better extensions for single bookmark searches (e.g. Selection Context Search - mini). This extension is catered towards those who want several search engines to choose from. 

The required effort to implement this feature is not in proportion to the use IMO. Thus, I will close this issue.
