### ISSUE TITLE
Urban Dictionary search is disabled

### ISSUE THREAD

**Issue by HighCommander4** [NumeriusNegidius/Context-Search#20]
I created a keyword search for [Urban Dictionary](http://www.urbandictionary.com/) and placed it in the "Search" folder of bookmarks, as instructed on the [add-on home page](https://addons.mozilla.org/en-US/firefox/addon/context-search-we/), and restarted.

However, in the extension's context submenu, the Urban Dictionary menu item is disabled. The menu items for other search engines are enabled and work fine; not sure what is different about Urban Dictionary.

**Comment by NumeriusNegidius** [comment]
Urban dictionary seems to use the form POST method. This isn't supported in WebExtensions (see issue #5). 

It seems you can add a bookmark manually in the "Searches" folder, as such: https://www.urbandictionary.com/define.php?term=%s which seems to work for me.

**Comment by HighCommander4** [comment]
Thanks, I can confirm that the described workaround makes the menu item work.
