### ISSUE TITLE
Add option to open tab to the right or at the end

### ISSUE THREAD

**Issue by eberhardweber** [NumeriusNegidius/Context-Search#21]
Hello all,

I see that there has already been discussion, in bugs #13 and #14, about the position of the new opened search tabs, which has prompted the current feature set of the add-on. For me, personally, the recent change was a major downgrade to usability, but I fully understand if there are others who do not think this way due to the way they work with tabs in Firefox.  

That said, I think there is an elegant solution: Context-Search could simply be written to respect the Firefox about:config value _browser.tabs.insertRelatedAfterCurrent_. That way, each user would get exactly the kind of tab opening style they have set for themselves.

I think this would be an ideal solution in a situation that is actually a pretty big deal for everyone. I know this means a lot to me as far as how I work in FF!

If working in accordance to the about:config value doesn't strike others as a suitable middle ground, then I'd be really happy if there was an option box introduced to the Context-Search add-on options to select whether the searches open at the end, or next to the old tab. That would do as well.

**Comment by NumeriusNegidius** [comment]
I'd really like the extension to be able to read the about:config values but [it's not possible and will likely never be](https://discourse.mozilla.org/t/webextension-read-write-access-to-about-config/12268/2).

However, I am definitely open for adding an option for this. I'll look in to it!

**Comment by NumeriusNegidius** [comment]
Fixed and released in version 0.9.8.
