### ISSUE TITLE
Is there any way to integrate Mycroft searches?

### ISSUE THREAD

**Issue by WolfganP** [NumeriusNegidius/Context-Search#22]
FOA, thx a lot for this extension. The Context Search addon I was using wasn't updated to WE and I was really missing this functionality.

I agree with other commenters on the fact that the ideal situation will be an integrated repository of search engines between this context search extension and FF's own implementation (about:preferences#search) so omnibar and context searches go hand in hand, but I also understand WE makes that impossible at this time.

So to simplify the installation of multiple context search engines, is there any way Mycroft project (http://mycroftproject.com/dlstats.html) could be integrated to this addon somehow?
Thanks!

**Comment by NumeriusNegidius** [comment]
Thanks for the suggestion! The keyword searches are by design made for the AwesomeBar in Firefox
