### ISSUE TITLE
display separators as separators

### ISSUE THREAD

**Issue by JohnGlassmyer** [NumeriusNegidius/Context-Search#23]
I keep a bookmark separator toward the end of my folder ("Searches") of keyword searches so that recently bookmarked / unsorted ones are separated from the list of previously sorted ones. (I suppose that other people use bookmark separators among their keyword-search bookmarks for other purposes.)

Currently, Context Search displays this bookmark separator as a blank entry in the context menu.

Would be great to have this separator displayed as a real menu separator.

**Comment by NumeriusNegidius** [comment]
Thanks for the suggestion! This was an issue in Firefox up until 57 and resolved in [1293853](https://bugzilla.mozilla.org/show_bug.cgi?id=1293853). [The documentation hasn't even been updated](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/BookmarkTreeNode). However, I have some working code that I will test a bit further, but I reckon this will be released within a week or so!

**Comment by WolfganP** [comment]
+1 on this one. I'm currently on FF57b6 and some separators are shown as empty items (some other aren't displayed at all). Thx!

**Comment by NumeriusNegidius** [comment]
Support for separators is included in version 1.0 available as we speak. In Firefox 57 and up.

**Comment by WolfganP** [comment]
Separators work perfectly. Thanks @NumeriusNegidius !
