### ISSUE TITLE
The root menu should read Search for "x" on...

### ISSUE THREAD

**Issue by NumeriusNegidius** [NumeriusNegidius/Context-Search#25]
To make the root menu more Firefoxy, it should read

> Search for "x" on...

just like the default search engine menu entry.

This depends on [bug 1370228](https://bugzilla.mozilla.org/show_bug.cgi?id=1370228) in Firefox to remove the ellipsis.

**Comment by despecial** [comment]
Plus: remove the "Search" prefix in the context menu.

"Search for X on > Google Maps"

**Comment by NumeriusNegidius** [comment]
As [bug 1370228](https://bugzilla.mozilla.org/show_bug.cgi?id=1370228) is resolved in Firefox 59, this is now fixed.
