### ISSUE TITLE
Search for text in copy/paste buffer

### ISSUE THREAD

**Issue by dranfox** [NumeriusNegidius/Context-Search#31]
With QuickSearch, when you right-clicked with no text selected, it checked the copy/paste buffer and, if it contained text, offered to search for that text.  I used this a lot when I encountered things in email or other apps that I wanted to search for.  Is this possible?  Thanks!

**Comment by NumeriusNegidius** [comment]
I will consider adding this once #19 and #3 is fixed.

**Comment by NumeriusNegidius** [comment]
Unless someone steps up, this won't be fixed. Closing this for now.
