### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by Floyd77** [NumeriusNegidius/Context-Search#33]
Is there any way to add google translate to the search engine list?

"Add a Keyword for this Search..." doesn't appear when I right click there, any suggestion or workaround?

Thanks a lot for this add-on, I found it as a replacement for "Context Search" not working since Firefox Quantum.

**Comment by capraibex** [comment]
Yes, there is a way. You have to manually add the URL to your 'Searches' bookmark folder:
https://translate.google.com/#auto/en/%s

- **#auto**

 means that Google Translate will automatically recognize the input language. You can change this to **#es** (spanish), **#de** (german), etc

- **en**

 is the output language. You can change this as well.

**Comment by Floyd77** [comment]
Thank you very much! I use it all the time.

**Comment by NumeriusNegidius** [comment]
I have added this question and solution to the Wiki.
