### ISSUE TITLE
Search ignores preferences regarding tab focus

### ISSUE THREAD

**Issue by Westcoastal** [NumeriusNegidius/Context-Search#34]
I have my browser set to _not_ switch tab focus when opening a new tab with search results (browser.search.context.loadInBackground is set to true). Unfortunately this extension appears to ignore that setting and always switches tab focus. 

Would it be possible to either make the extension adhere to the browser.search.context.loadInBackground setting, or else provide a preference in the extension settings that would allow us to set tab focus behaviour?

Thanks for all your hard work!

**Comment by NumeriusNegidius** [comment]
Extensions cannot access browser settings currently. But you can go to Add-ons Manager and change the pref for Context Search. Just uncheck ”Switch to the tab immediately”.

**Comment by Westcoastal** [comment]
Thanks, didn't see that setting.
