### ISSUE TITLE
Support custom favicons

### ISSUE THREAD

**Issue by somini** [NumeriusNegidius/Context-Search#36]
Many thanks for keeping this extension alive, I don't think I could use Firefox without it.

---

I have some search engines the use DuckDuckGo with a custom `site:` parameter, and while I can configure them correctly, I'm unable to change its favicon to the target site.

How is the favicon retrieved, does it come directly from the bookmarks cache? Is it possible to replace it in the bookmarks, perhaps with a different extension?

**Comment by NumeriusNegidius** [comment]
Favicons as such aren't supported at all in the WebExtensions API unfortunately. The current implementation is a temporary hack (see issue #9). I can't see an easy way to implement your request in the extension and as such I will close the issue.
