### ISSUE TITLE
Disabled in Firefox 57.03 (64 bit) on Windows 10

### ISSUE THREAD

**Issue by orotau** [NumeriusNegidius/Context-Search#39]
Hi there
The extension has been disabled for me in firefox 57.03 (64 bit) on Windows 10
This is the error message
"Context Search WebExtension could not be verified for use in Firefox and has been disabled"

There is a link to this page
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by NumeriusNegidius** [comment]
Are you still having this issue? I've noticed once that the signing failed when the add-on was updated in my browser at the same time as it was submitted to addons.mozilla.org (which seems to correlate with your experience). If I recall correctly the issue was remedied by a restart of Firefox.

**Comment by orotau** [comment]
I tried restarting Firefox but that didn't work, so I removed the extension and reinstalled it and the problem went away. Thanks for response and thanks for the extension!
