### ISSUE TITLE
Firefox 57.0.4 refuses to add keyword to a folder

### ISSUE THREAD

**Issue by clamtastic** [NumeriusNegidius/Context-Search#42]
Firefox 57.0.4 refuses to save a keyword to a folder.

**Comment by NumeriusNegidius** [comment]
Sorry for late reply. 

Are you trying to add a keyword to a folder or to a bookmark? The former is impossible, but the latter should work. 

The adding of keywords to bookmarks is a Firefox feature and nothing Context Search WE can tamper with, so if you still have problems adding keywords to bookmarks, please consult support.mozilla.org.
