### ISSUE TITLE
Searche engines are disabled (not functioning) because the "S" in "%S" is in capital letter

### ISSUE THREAD

**Issue by brain8891** [NumeriusNegidius/Context-Search#45]
Many of my search engines were disabled(greyed out). I didn't realize why till I notice that if I changed the Capital "S" in "%S" with a lower case "s" then it would become active.

**Comment by NumeriusNegidius** [comment]
A general replace %S with %s will not be implemented. The biggest reason is that Firefox creates the keyword searches with %s. According to issue #40, %s and %S differ in meaning. I'm closing this issue and keeping the other issue open.
