### ISSUE TITLE
New Firefox permission: Access your data for all websites

### ISSUE THREAD

**Issue by qouoq** [NumeriusNegidius/Context-Search#52]
About a week ago, Firefox informed me that the Context Search extension was requiring a new permission, namely "Access your data for all websites".
I would like to ask, why is this new permission required?

**Comment by NumeriusNegidius** [comment]
It’s for enabling anchor text and image url search. Up until version 1.1 the extension could only search for selected text. To do that I had to add a content script and those require access to all websites to work on all websites. 

This extension doesn’t modify anything in Firefox (except the addon’s settings). It just reads data and populate a menu. 

The permissions thing is not very fine grained.

**Comment by qouoq** [comment]
Understood, thanks for the clear answer :)
