### ISSUE TITLE
Search to all sites in one folder

### ISSUE THREAD

**Issue by nonobio** [NumeriusNegidius/Context-Search#53]
Hi,
First, thanks a lot for your extension, i replace my old "smart search" with it :)

Could you add an option to search to all sites in a selected folder in one click ?

I also use the great addon "Selection Search" in Google Chrome.

Thanks

**Comment by brain8891** [comment]
Right clicking on a folder, or alternatively middle clicking on a folder . Or both!

**Comment by NumeriusNegidius** [comment]
This is now fixed. Coming in the next release.
