### ISSUE TITLE
Switch to new tab immediately

### ISSUE THREAD

**Issue by ygoe** [NumeriusNegidius/Context-Search#54]
This option used to work just fine, but doesn't anymore. Using all the latest stable versions, so a recent update of either this add-on or firefox must have broken it.

**Comment by NumeriusNegidius** [comment]
It should be fixed in 2.0.1, available on AMO in a couple of minutes. Thanks for submitting the bug!

**Comment by ygoe** [comment]
Confirmed. I had to clear and reset the option in the add-on settings to reactivate this feature.
