### ISSUE TITLE
CSO behaves weird in iframes

### ISSUE THREAD

**Issue by Zitronella** [NumeriusNegidius/Context-Search#55]
I mark the word "test" in https://www.google.de/search?q=test and search with the extension afterwards. It is working.
Then I mark a word in the iframe of https://codepen.io/GBora/pen/VLYyzY and in the context menu it still looks for the word "test". The same thing, if I enter an editor with the address
data: text / html, <html contenteditable> and type in xxxxx there and then search in the context menu, it is still looking for "test"
The same also when i search something on site https://addons.mozilla.org/en-US/firefox/addon/context-search-we/

With Firefox 59 all these things works correct. Could you please fix it in your wonderful extension?

**Comment by NumeriusNegidius** [comment]
The second part of the issue, about not working on addons.mozilla.org is work in progress, see [issue 49]( #49).

The second part needs some more investigation, I'll need to look in to it.

**Comment by NumeriusNegidius** [comment]
This should be fixed in code now, will be released on AMO soon.
