### ISSUE TITLE
Localize Getting started

### ISSUE THREAD

**Issue by NumeriusNegidius** [NumeriusNegidius/Context-Search#60]

**Comment by Kadilov** [comment]
Is it about a guide that should be opened when there are no search engines configured? Actually this is my guess about how extension should work, because clicking on this menu item did nothing for me in my both Windows 10 and Linux OSs.

**Comment by NumeriusNegidius** [comment]
Thanks for catching that. This is fixed per #77

**Comment by NumeriusNegidius** [comment]
Getting started can now be localized by adding a translated "help.html" file in the /_locales/{language_code} directory + changing the "help_locale" string to the translated language code.
