### ISSUE TITLE
Context-Search not functioning in new window

### ISSUE THREAD

**Issue by salionPL** [NumeriusNegidius/Context-Search#66]
1. Go to http://release24.pl/ and click commentary button:
![screenshot_2018-10-31 release24 pl - release filmow seriali i gier](https://user-images.githubusercontent.com/38588787/47789919-356aa280-dd16-11e8-89df-59d51ed12a89.png)
2. New window is open
3. Context-Search not functioning in this new window :(

**Comment by NumeriusNegidius** [comment]
As the website tries to hide all browser chrome in the popup windows (toolbars, locationbar, etc), it effectively stops the extension from opening a new tab within that window, throwing an error. 

In a0f70a6, the code that creates a new tab is now a promise, and if an error is thrown, it tries to create a new tab without openerTabId. I'm still testing it out, and if nothing breaks will be released in the next version.
