### ISSUE TITLE
Add a toolbar button with search engines for searching the entered word in the AwesomeBar

### ISSUE THREAD

**Issue by janvandyk** [NumeriusNegidius/Context-Search#67]
Hey there,

Thank you for this great Addon!

I would like to suggest a feature I know from the [classic search bar extension](https://github.com/tiansh/classical-search-bar) . It implements the "simulation" of a "classical search bar" by adding a search engine switch button with a dropdown-menu. I also suggested [there](https://github.com/tiansh/classical-search-bar/issues/10) to merge this functionality with this extension here. 

Thank you and best regards
Jan

**Comment by NumeriusNegidius** [comment]
Interesting proposal. I'm usually not too keen on adding non-core functionalities. I'll think on it for now. Cheers

**Comment by NumeriusNegidius** [comment]
OK, so now about one year later, with even more limited time, I really don't understand what this issue is about. Either I did at the time or I was drunk. Closing this for now...
