### ISSUE TITLE
OpenCritic

### ISSUE THREAD

**Issue by Floyd77** [NumeriusNegidius/Context-Search#68]
Hi, is there any way to add OpenCritic.com to Context-Search?

Thanks.

**Comment by NumeriusNegidius** [comment]
It doesn't seem like opencritic.com has a search _page_, but rather a JSON file that feeds the search box thingy. I can't see they support opensearch or similar either, so i guess you can't context search with any extension until they add one. 

If this changes or if you find a way, please let me know! Cheers

**Comment by NumeriusNegidius** [comment]
Won't be able to do anything about this... Closing it
