### ISSUE TITLE
Add Site Search

### ISSUE THREAD

**Issue by Speciesx** [NumeriusNegidius/Context-Search#7]
Add 'Site Search'

**Comment by NumeriusNegidius** [comment]
I don't understand what you mean by that.

**Comment by Speciesx** [comment]
Context Search X has his feature.

**Comment by NumeriusNegidius** [comment]
What feature?

**Comment by Speciesx** [comment]
'Site Search'

**Comment by NumeriusNegidius** [comment]
Don't assume people can read your mind. "Site search" means norhing to me. If you won't explain this issue with more than 2 words, please don't comment further.

**Comment by Speciesx** [comment]
> Modifications:
> 4. Site Search (additional item in submenu): Searches for selected text in current site using Google

https://addons.mozilla.org/de/firefox/addon/context-search-x

**Comment by NumeriusNegidius** [comment]
No.

**Comment by NumeriusNegidius** [comment]
See also #18
