### ISSUE TITLE
Middle clicking on [Search for "example  text..."] searches with the default search engine (feature request)

### ISSUE THREAD

**Issue by brain8891** [NumeriusNegidius/Context-Search#70]
When middle clicking on [Search for "example  text..."] it would search with the default search engine. 
Reason: 
right now, you have to click on [Search for "example  text..."]  and then select the default/first search engine in your list, which you use more frequently. 

![mouse](https://user-images.githubusercontent.com/7104190/55672499-c25ced80-58ac-11e9-9a85-62a8095ec896.png)

**Comment by NumeriusNegidius** [comment]
This could be possible now according to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData) (section button).

I'll look in to this!

**Comment by NumeriusNegidius** [comment]
Looking at it now: there are extensions for searching single search engines and there's a built in Firefox feature for searching a default search engine. What would CSO contribute with this? 

Closing this issue until more info is proveded
