### ISSUE TITLE
Add a guide for how to reposition CSO's placement in the main context menu

### ISSUE THREAD

**Issue by brain8891** [NumeriusNegidius/Context-Search#71]
I could volunteer:

Adding step by step guide on how to move the  Context Search Origin to the top of context-menu.
preferably in the Add-on description and the FAQ. 

![mouse](https://user-images.githubusercontent.com/7104190/55672698-ee796e00-58ae-11e9-88ff-9ec1c1381297.png)

Thank you for your hard work.

**Comment by NumeriusNegidius** [comment]
I'm unaware on how to do this myself, could you give me more info on this? Thanks

**Comment by NumeriusNegidius** [comment]
This is tracked in [Bug 1370735 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1370735). Unless that is fixed I can't do anything about this. Closing for now.
