### ISSUE TITLE
feature request floating/popup windows search 

### ISSUE THREAD

**Issue by brain8891** [NumeriusNegidius/Context-Search#72]
For some website you don't want  the search to be opened in a new window, rather a popup or floating window on the page it self. For example: search something on Google Images, dictionaries, google translate.

How to open in a floating window: 
1- Right clicking on the search engine and choosing open in a floating window
2- If double right clicked on a search engine it would be opened in a floating window
3- having a button on beside each search engine, and you could add additional option for each search engine floating windows size, user agent, zoom level, scroll position(meaning, it would scroll a certain amount up or down) 

Additional options:
1- having the option to change the user agent to a mobile device.
2- changing the window side per search website.
3- Changing the zoom level per website. 
4- scroll position
5- floating window position, either where the mouse is, in one of the corners of the webpage 

Reasons:
1- as someone who reads in multiple languages and do lots of research, I use many Dictionary websites. For instance, you are reading  a manufacturer website and you see a name of a bizarre contraption you would select the text and search in google images right there on the page, without the cumbersome process of going to a new tab.
2- why different Add-on? Because this will be more versatile where you could add many services and not install various add-ons. I can

**Comment by NumeriusNegidius** [comment]
Thanks for the request. This seems like quite the task. I'm unfortunately not up to it. If you are, please fork and/or make a pull request.

Closing this for now.
