### ISSUE TITLE
Always open search result in a new tab

### ISSUE THREAD

**Issue by salionPL** [NumeriusNegidius/Context-Search#74]
**Please add options: Always open search result in a new tab (on use middle-click or left-click)**

![always](https://user-images.githubusercontent.com/38588787/58100998-13b40880-7bdf-11e9-8132-3c34ce051e51.jpg)

**Comment by NumeriusNegidius** [comment]
Would you care to explain the reasoning behind this suggestion?

**Comment by salionPL** [comment]
The default search results in firefox open in the new tab after the left click. But clicking on the links performs the middle click to open in the new tab. It can be confusing to me. And I sometimes click with the left button and sometimes with the middle button to search. I would like to always open the results in a new tab, no matter which one I click on.

**Comment by NumeriusNegidius** [comment]
Fixed per version 2.6
