### ISSUE TITLE
Working only intermittently

### ISSUE THREAD

**Issue by Ainson** [NumeriusNegidius/Context-Search#80]
I would say 50% of the time Context-Search is present in the context menu, and 50% it's not.

I have only one Searches folder, and have even tried to move it around the Toolbar / Menu / Other folders, but it makes no difference.

Any ideas? 

I'm on Windows 7 x64

**Comment by Ainson** [comment]
Might add that I get the odd sqlite error when I move or copy bookmarks.

I have tried to install sqlite on Windows, but not any sqlite Firefox extension.

I have plenty of hard disk space and memory so that's not an issue.

**Comment by NumeriusNegidius** [comment]
I've never run in to this issue and I can't reproduce this bug, unfortunately. Perhaps you could try resetting Firefox or create a new profile to see if the problem persists?

**Comment by Ainson** [comment]
I tried a new profile but still the same. Seems to be something with bookmarks in Firefox as I also have some issues with that. (can't add using the star).

I'll update here if I do a reinstall of Firefox or find another fix.
