### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by Reggie521** [NumeriusNegidius/Context-Search#82]
Favicons in the right click menu seem really low quality and sometimes just disappear, leaving a generic icon. Could a different, more reliable service be used? 

<img width="97" alt="favicons" src="https://user-images.githubusercontent.com/35973596/129106390-4fa45628-ffc8-4aac-bfc9-048891c0c7b9.png">

**Comment by ygoe** [comment]
Looks like the icons are loaded with a size of 16 pixels. I've used the Google service with a size of 32 pixels in one of my apps. Here's the URL for that:

`https://www.google.com/s2/favicons?sz=32&domain_url=example.com`

(domain name without a scheme/protocol, just the host name)

This extension seems to use the same service, but without the size (sz) parameter. It could be set depending on the current screen resolution. Maybe the web API [`Window.devicePixelRatio`](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) is available in extensions as well. I'd say use these values:

* = 1 → sz=16
* ≤ 2 → sz=32
* > 2 → sz=48

If these icons are cached somewhere (I don't know), then it could be a problem when the screen resolution changes after the icons have been loaded. But if they're fetched every time (with the current size parameter), it should be alright.

**Comment by NumeriusNegidius** [comment]
@ygoe: Thanks! This works beautifully. Firefox deals with the scaling, and 32px seems a good size on my test machines. Coming in the next version (soon).

@Reggie521: The disappearing icons I cannot do much about. I don't know of any third party service that is as reliable as Google S2. 

Closing this bug. See issue #9 also.
